varsion: 2.1

executors:
  default:
    - image: circleci/node:12.16.1
  working_directory: ~/repo

##
# commands
##

commands:
  restore_npm:
    - restore_cache:
        keys:
          - yarn-packages-{{ checksum "yarn.lock" }}
  save_npm:
    steps:
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}

##
# jobs
##

jobs:
  test-lint:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run: yarn install --frozen-lockfile
      - save_npm
      - run: yarn lint
      - run: yarn test

##
# workflows
##

workflows:
  test_my_app:
    jobs:
      - test-lint
